name: CP-AMM-SDK

on:
  pull_request:
    branches:
      - main

env:
  SOLANA_CLI_VERSION: 2.1.0
  NODE_VERSION: 18.20.6
  ANCHOR_CLI_VERSION: 0.31.0

jobs:
  sdk_changed_files:
    runs-on: ubuntu-latest
    outputs:
      program: ${{steps.changed-files-specific.outputs.any_changed}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get specific changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v18.6
        with:
          files: |
            src
            tests

  sdk_test:
    runs-on: ubuntu-latest
    needs: sdk_changed_files
    if: needs.sdk_changed_files.outputs.program == 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-solana
      - uses: ./.github/actions/setup-dep
      # Install pnpm
      - uses: pnpm/action-setup@v3 # docs https://pnpm.io/continuous-integration#github-actions
        with:
          version: 9.5.0 # Optional: specify a pnpm version
      # Install rust + toolchain
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy
      # Cache rust, cargo
      - uses: Swatinem/rust-cache@v1
      # Cache node_modules
      - uses: actions/cache@v4
        id: cache-node-modules
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('./package-lock.json') }}
      # Testing
      - run: npm install && npm run test
        shell: bash
